<template>
  <SupplierModuleLayout>
    <header class="sp-page-head">
      <div><div class="sp-eyebrow">Upstream Operations / Live</div><h1>上游运维驾驶舱</h1><p class="sp-subtitle">先处理影响真实流量的问题，再判断账号池健康与成本变化。</p></div>
      <div class="sp-controls"><div class="sp-segmented"><button :class="{ active: range === '24h' }" type="button" @click="range = '24h'">24 小时</button><button :class="{ active: range === '7d' }" type="button" @click="range = '7d'">7 天</button></div><button class="sp-button" type="button" @click="showToast('驾驶舱数据已刷新')">刷新数据</button><button class="sp-button primary" type="button" @click="showToast('账号巡检演示已提交')">执行账号巡检</button></div>
    </header>

    <div class="sp-data-note"><b>数据完整</b><span>统计生成于 09:42:18；账号实时状态为当前值，流量与成本按所选时间范围统计。</span></div>

    <section class="sp-risk-grid">
      <article v-for="risk in risks" :key="risk.key" class="sp-risk-card" :class="[`sp-${risk.tone}`, { selected: selectedRisk === risk.key }]" @click="selectedRisk = risk.key"><div class="sp-risk-label">{{ risk.label }}</div><div class="sp-risk-value">{{ risk.value }}</div><div class="sp-risk-foot">{{ risk.foot }}</div></article>
    </section>

    <section class="sp-grid-main">
      <div class="sp-panel">
        <header class="sp-panel-head"><div class="sp-panel-title"><span class="sp-section-index">01</span><div><h2>高影响异常账号</h2><span>已按“{{ activeRiskLabel }}”筛选演示数据</span></div></div><div class="sp-tools"><span class="sp-filter-pill">影响优先</span><span class="sp-filter-pill">有效账号池</span><button class="sp-button small ghost" type="button" @click="selectedRisk = 'all'">查看全部 17</button></div></header>
        <div class="sp-table-wrap"><table class="sp-table"><thead><tr><th>风险</th><th>供应商 / 账号</th><th>业务影响</th><th>倍率</th><th>余额</th><th>状态</th></tr></thead><tbody><tr v-for="issue in filteredIssues" :key="issue.account" class="clickable" @click="selectedIssue = issue"><td><span class="sp-severity" :class="issue.severityTone">{{ issue.severity }}</span></td><td><div class="sp-account-name">{{ issue.account }}</div><div class="sp-subline">{{ issue.provider }} · {{ issue.group }}</div></td><td><span class="sp-metric-strong">{{ issue.requests }}</span><div class="sp-subline">请求 · 成功率 {{ issue.success }}</div></td><td><span class="sp-metric-strong">{{ issue.rate }}</span><div class="sp-subline" :class="issue.rateTone">{{ issue.rateHint }}</div></td><td><span class="sp-metric-strong">{{ issue.balance }}</span><div class="sp-subline" :class="{ 'sp-up': issue.balanceRisk }">{{ issue.balanceHint }}</div></td><td><span class="sp-tag" :class="issue.statusTone">{{ issue.status }}</span></td></tr><tr v-if="!filteredIssues.length"><td colspan="6">该筛选下没有演示记录</td></tr></tbody></table></div>
      </div>

      <aside class="sp-panel"><header class="sp-panel-head"><div class="sp-panel-title"><span class="sp-section-index">02</span><div><h2>有效账号池健康</h2><span>已排除 2 个禁用供应商和 11 个禁用账号</span></div></div><span class="sp-tag warn">需关注</span></header><div class="sp-health-body"><div class="sp-health-score"><div class="sp-ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="50" fill="none" stroke="var(--sp-soft)" stroke-width="8"/><circle cx="60" cy="60" r="50" fill="none" stroke="var(--sp-amber)" stroke-width="8" stroke-linecap="square" stroke-dasharray="314" stroke-dashoffset="47"/></svg><div><strong>85%</strong><small>综合健康度</small></div></div><div class="sp-health-copy"><h3>账号池可继续承载流量</h3><p>主要风险集中在火山引擎企业 A 组。5 个异常账号覆盖 38.6% 的近期流量，建议优先完成测试与调度调整。</p></div></div><div class="sp-health-list"><div v-for="item in healthItems" :key="item.label" class="sp-health-item"><b :class="item.tone">{{ item.value }}</b><span>{{ item.label }}</span></div></div></div></aside>
    </section>

    <section class="sp-wide-grid">
      <div class="sp-panel"><header class="sp-panel-head"><div class="sp-panel-title"><span class="sp-section-index">03</span><div><h2>倍率与最低倍率分析</h2><span>同供应商、同上游分组比较 · 基于最近一次同步</span></div></div><div class="sp-tools"><button v-for="tab in rateTabs" :key="tab" class="sp-pill" :class="{ active: rateTab === tab }" type="button" @click="rateTab = tab">{{ tab }}</button></div></header><div class="sp-table-wrap"><table class="sp-table"><thead><tr><th>供应商 / 分组</th><th>承载账号</th><th>当前倍率</th><th>同组最低</th><th>倍率差</th><th>预计额外成本</th></tr></thead><tbody><tr v-for="item in rateRows" :key="item.provider"><td><div class="sp-account-name">{{ item.provider }}</div><div class="sp-subline">{{ item.group }}</div></td><td>{{ item.account }}</td><td :class="item.risk ? 'sp-up' : ''">{{ item.current }}</td><td><span class="sp-tag" :class="item.lowest === '无法比较' ? '' : 'good'">{{ item.lowest }}</span></td><td><div v-if="item.delta !== '—'" class="sp-rate-cell">{{ item.delta }}<span v-if="item.risk" class="sp-rate-line"><i :style="{ width: item.width }"></i></span></div><span v-else>—</span></td><td><b v-if="item.cost !== '—'">{{ item.cost }}</b><span v-else>—</span></td></tr></tbody></table></div></div>

      <div class="sp-panel"><header class="sp-panel-head"><div class="sp-panel-title"><span class="sp-section-index">04</span><div><h2>成本与余额趋势</h2><span>倍率变化以事件标记展示</span></div></div><span class="sp-filter-pill">{{ range === '24h' ? '24 小时' : '7 天' }}</span></header><div class="sp-chart-wrap"><div class="sp-chart-kpis"><div class="sp-chart-kpi"><span>上游成本</span><b>¥ 6,842</b></div><div class="sp-chart-kpi"><span>余额消耗</span><b>¥ 7,106</b></div><div class="sp-chart-kpi"><span>预计可用</span><b>8.4 天</b></div></div><svg class="sp-chart" viewBox="0 0 620 190" preserveAspectRatio="none" aria-label="成本趋势图"><g class="sp-chart-grid"><line x1="0" y1="35" x2="620" y2="35"/><line x1="0" y1="80" x2="620" y2="80"/><line x1="0" y1="125" x2="620" y2="125"/><line x1="0" y1="170" x2="620" y2="170"/></g><path d="M0,152 C40,146 52,122 92,127 S148,142 185,108 S245,100 278,118 S330,91 370,96 S426,72 470,83 S540,43 620,55" fill="none" stroke="var(--sp-cyan)" stroke-width="3"/><path d="M0,166 C55,157 85,154 120,142 S190,133 235,125 S295,119 340,102 S405,98 455,88 S540,79 620,65" fill="none" stroke="var(--sp-amber)" stroke-width="2" stroke-dasharray="5 5"/><line x1="470" y1="25" x2="470" y2="170" stroke="var(--sp-red)" stroke-width="1" stroke-dasharray="3 4"/><circle cx="470" cy="83" r="5" fill="var(--sp-red)"/><text x="477" y="24" class="sp-chart-label">倍率上涨 4 项</text><text x="0" y="186" class="sp-chart-label">00:00</text><text x="145" y="186" class="sp-chart-label">06:00</text><text x="300" y="186" class="sp-chart-label">12:00</text><text x="455" y="186" class="sp-chart-label">18:00</text><text x="585" y="186" class="sp-chart-label">现在</text></svg></div></div>
    </section>

    <section class="sp-panel" style="margin-bottom: 14px"><header class="sp-panel-head"><div class="sp-panel-title"><span class="sp-section-index">05</span><div><h2>供应商运行概览</h2><span>按业务风险排序，而不是固定排序</span></div></div><button class="sp-button small ghost" type="button" @click="router.push('/admin/supplier-management/providers')">进入供应商管理</button></header><div class="sp-provider-grid"><article v-for="provider in providers" :key="provider.name" class="sp-provider-card" @click="selectedProvider = provider"><div class="sp-provider-head"><span class="sp-provider-name">{{ provider.name }}</span><i class="sp-provider-status" :class="provider.tone"></i></div><div class="sp-provider-main"><div><b :class="provider.textTone">{{ provider.state }}</b><span>运行状态</span></div><span>{{ provider.issue }}</span></div><div class="sp-provider-stats"><div class="sp-provider-stat"><b>{{ provider.accounts }}</b><span>可调度账号</span></div><div class="sp-provider-stat"><b>{{ provider.success }}</b><span>成功率</span></div><div class="sp-provider-stat"><b>{{ provider.cost }}</b><span>24h 成本</span></div><div class="sp-provider-stat"><b>{{ provider.balance }}</b><span>余额可用</span></div></div></article></div></section>

    <section class="sp-panel"><header class="sp-panel-head"><div class="sp-panel-title"><span class="sp-section-index">06</span><div><h2>自动化任务摘要</h2><span>只展示异常、运行中和关键任务；完整记录进入任务中心</span></div></div><button class="sp-button" type="button" @click="router.push('/admin/supplier-management/automations')">打开全宽任务中心</button></header><div class="sp-task-list"><div v-for="task in summaryTasks" :key="task.name" class="sp-task-row"><div><div class="sp-task-name">{{ task.name }}</div><div class="sp-task-meta">{{ task.meta }}</div></div><span class="sp-tag" :class="task.tone">{{ task.status }}</span><div><b>{{ task.checked }}</b><div class="sp-task-meta">{{ task.checkedLabel }}</div></div><div><template v-if="task.progress"><div class="sp-progress"><i :style="{ width: task.progress }"></i></div></template><b v-else :class="task.tone === 'bad' ? 'sp-up' : ''">{{ task.changed }}</b><div class="sp-task-meta">{{ task.changedLabel }}</div></div><div><b>{{ task.duration }}</b><div class="sp-task-meta">{{ task.durationLabel }}</div></div><button class="sp-button small" :class="{ danger: task.tone === 'bad' }" type="button" @click="router.push('/admin/supplier-management/automations')">{{ task.action }}</button></div></div></section>

    <div class="sp-footer-note"><span>静态设计原型 · 所有数据均为演示数据</span><span>点击风险卡和异常账号可体验筛选与处置抽屉</span></div>

    <SupplierDrawer :show="Boolean(selectedIssue || selectedProvider)" :title="selectedIssue ? `${selectedIssue.provider} / ${selectedIssue.account}` : selectedProvider?.name || ''" :eyebrow="selectedIssue ? 'INCIDENT DETAIL' : 'PROVIDER DETAIL'" @close="closeDrawer">
      <template v-if="selectedIssue"><div class="sp-alert">{{ selectedIssue.reason }}</div><div class="sp-detail-grid"><div class="sp-detail-cell"><span>近 24h 请求</span><b>{{ selectedIssue.requests }}</b></div><div class="sp-detail-cell"><span>成功率</span><b>{{ selectedIssue.success }}</b></div><div class="sp-detail-cell"><span>当前倍率</span><b>{{ selectedIssue.rate }}</b></div><div class="sp-detail-cell"><span>余额预计可用</span><b :class="{ 'sp-up': selectedIssue.balanceRisk }">{{ selectedIssue.balanceHint }}</b></div></div><div class="sp-drawer-actions"><button class="sp-button primary" type="button" @click="showToast('账号测试已提交')">立即测试</button><button class="sp-button" type="button" @click="showToast('重新同步已提交')">重新同步</button><button class="sp-button danger" type="button" @click="showToast('调度调整预览已打开')">调整调度</button></div><div class="sp-timeline"><h4>建议处置顺序</h4><div class="sp-event"><b>先验证当前连接与模型覆盖</b><p>确认错误是否仍可复现，并检查同组健康账号容量。</p></div><div class="sp-event"><b>再决定暂停或切换调度</b><p>优先降低真实业务影响，再处理倍率和成本问题。</p></div></div></template>
      <template v-else-if="selectedProvider"><div class="sp-alert">{{ selectedProvider.name }} 的运行状态、账号健康、成本和余额均使用原型演示数据。</div><div class="sp-detail-grid"><div class="sp-detail-cell"><span>可调度账号</span><b>{{ selectedProvider.accounts }}</b></div><div class="sp-detail-cell"><span>成功率</span><b>{{ selectedProvider.success }}</b></div><div class="sp-detail-cell"><span>24h 成本</span><b>{{ selectedProvider.cost }}</b></div><div class="sp-detail-cell"><span>余额可用</span><b>{{ selectedProvider.balance }}</b></div></div><div class="sp-drawer-actions"><button class="sp-button primary" type="button" @click="router.push('/admin/supplier-management/providers')">进入供应商管理</button></div></template>
    </SupplierDrawer>
    <Transition name="sp-fade"><div v-if="toast" class="sp-toast">{{ toast }}</div></Transition>
  </SupplierModuleLayout>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { SupplierDrawer, SupplierModuleLayout } from '@/components/admin/supplier-management'

interface IssueRow { severity: string; severityTone: string; account: string; provider: string; group: string; requests: string; success: string; rate: string; rateHint: string; rateTone: string; balance: string; balanceHint: string; balanceRisk?: boolean; status: string; statusTone: string; tags: string[]; reason: string }
interface ProviderCard { name: string; tone: string; textTone: string; state: string; issue: string; accounts: string; success: string; cost: string; balance: string }
const router = useRouter()
const range = ref<'24h' | '7d'>('24h')
const selectedRisk = ref('critical')
const rateTab = ref('风险分组')
const selectedIssue = ref<IssueRow | null>(null)
const selectedProvider = ref<ProviderCard | null>(null)
const toast = ref('')
let toastTimer: number | undefined
const risks = [
  { key: 'critical', tone: 'red', label: '紧急异常账号', value: '3', foot: '其中 2 个正在承载流量' }, { key: 'traffic', tone: 'red', label: '承载流量的异常账号', value: '5', foot: '覆盖近 24h 请求量 38.6%' }, { key: 'rate-up', tone: 'orange', label: '本次同步倍率上涨', value: '4', foot: '最高上涨 18.2%' }, { key: 'not-lowest', tone: 'amber', label: '非最低倍率承载账号', value: '6', foot: '预计多支出 ¥86.40 / 日' }, { key: 'balance', tone: 'orange', label: '预计余额不足 3 天', value: '4', foot: '其中 1 个不足 24 小时' }, { key: 'sync', tone: 'blue', label: '账号同步冲突', value: '2', foot: '等待人工确认匹配关系' }, { key: 'task', tone: 'violet', label: '自动任务异常', value: '1', foot: '余额采样连续失败 2 次' }, { key: 'disabled', tone: 'muted-tone', label: '已禁用资源', value: '2 / 11', foot: '供应商 / 上游账号 · 点击查看' },
]
const issues: IssueRow[] = [
  { severity: '紧急', severityTone: 'critical', account: 'prod-cn-02', provider: '火山引擎', group: '企业 A 组', requests: '12,684', success: '71.4%', rate: '1.25', rateHint: '↑ 13.6% · 非最低', rateTone: 'sp-up', balance: '¥ 326', balanceHint: '预计 0.8 天', balanceRisk: true, status: '测试失败', statusTone: 'bad', tags: ['critical', 'traffic', 'rate-up', 'not-lowest'], reason: '账号测试连续失败 3 次，但近 24 小时仍承载 12,684 次请求。' },
  { severity: '紧急', severityTone: 'critical', account: 'gpt-primary', provider: 'New API', group: 'vip-3', requests: '9,210', success: '98.8%', rate: '1.10', rateHint: '并列最低', rateTone: 'sp-down', balance: '$ 48', balanceHint: '预计 0.7 天', balanceRisk: true, status: '余额紧急', statusTone: 'bad', tags: ['critical', 'traffic', 'balance'], reason: '余额预计不足 20 小时，账号承担该供应商 64% 的请求流量。' },
  { severity: '高', severityTone: 'high', account: 'claude-route-01', provider: 'OpenRouter', group: 'Claude 专线', requests: '6,842', success: '99.2%', rate: '1.18', rateHint: '最低 1.05 · +12.4%', rateTone: 'sp-up', balance: '$ 1,840', balanceHint: '预计 16.2 天', status: '非最低倍率', statusTone: 'warn', tags: ['traffic', 'not-lowest', 'rate-up'], reason: '当前承载账号不再是同供应商、同分组最低倍率，预计每日多支出 ¥42.60。' },
  { severity: '高', severityTone: 'high', account: 'codex-07', provider: '自建中转', group: 'Codex', requests: '3,105', success: '96.7%', rate: '0.96', rateHint: '无法比较', rateTone: '', balance: '¥ 2,301', balanceHint: '预计 23.8 天', status: '同步冲突', statusTone: 'warn', tags: ['traffic', 'sync'], reason: '上游账号已存在，但无法唯一匹配本地账号；当前仍有历史流量。' },
  { severity: '提醒', severityTone: 'medium', account: 'gemini-backup', provider: 'New API', group: 'Google', requests: '881', success: '99.6%', rate: '0.80', rateHint: '唯一最低', rateTone: 'sp-down', balance: '$ 122', balanceHint: '预计 2.6 天', status: '低余额', statusTone: 'warn', tags: ['balance'], reason: '近 7 日平均消耗上升，预计余额将在 2.6 天后耗尽。' },
]
const healthItems = [{ value: '68', label: '有效账号' }, { value: '54', label: '当前可调度 · 79.4%' }, { value: '31', label: '近 24h 有请求' }, { value: '97.2%', label: '近期测试成功率' }, { value: '5', label: '承载流量异常', tone: 'sp-up' }, { value: '4', label: '无本地匹配', tone: 'sp-amber' }]
const rateTabs = ['风险分组', '最近变化', '全部分组']
const rateRows = [{ provider: 'OpenRouter', group: 'Claude 专线 · 4 个有效账号', account: 'claude-route-01', current: '1.18 ↑', lowest: '1.05 · route-03', delta: '+12.4%', width: '78%', cost: '¥ 42.60 / 日', risk: true }, { provider: '火山引擎', group: '企业 A 组 · 6 个有效账号', account: 'prod-cn-02', current: '1.25 ↑', lowest: '1.10 · prod-cn-04', delta: '+13.6%', width: '86%', cost: '¥ 31.20 / 日', risk: true }, { provider: 'New API', group: 'vip-3 · 3 个有效账号', account: 'gpt-primary', current: '1.10', lowest: '1.10 · 并列最低', delta: '0%', width: '0%', cost: '无额外成本', risk: false }, { provider: '自建中转', group: 'Codex · 分组键缺失', account: 'codex-07', current: '0.96', lowest: '无法比较', delta: '—', width: '0%', cost: '—', risk: false }]
const providers: ProviderCard[] = [{ name: '火山引擎', tone: 'bad', textTone: 'sp-up', state: '高风险', issue: '2 个严重异常', accounts: '18 / 24', success: '89.1%', cost: '¥ 2,408', balance: '3.2 天' }, { name: 'New API', tone: 'warn', textTone: 'sp-amber', state: '余额风险', issue: '1 个账号不足 1 天', accounts: '13 / 15', success: '98.9%', cost: '¥ 1,926', balance: '1.8 天' }, { name: 'OpenRouter', tone: 'warn', textTone: 'sp-amber', state: '成本偏高', issue: '3 个非最低倍率', accounts: '10 / 11', success: '99.2%', cost: '¥ 1,554', balance: '16.2 天' }, { name: '自建中转', tone: '', textTone: 'sp-down', state: '稳定', issue: '无严重异常', accounts: '13 / 14', success: '99.6%', cost: '¥ 954', balance: '23.8 天' }]
const summaryTasks = [{ name: '上游账号同步', meta: '每 15 分钟 · 下次 09:55', status: '正常', tone: 'good', checked: '248', checkedLabel: '检查账号', changed: '6', changedLabel: '产生变更', duration: '1m 42s', durationLabel: '上次耗时', action: '查看' }, { name: '账号健康巡检', meta: '每 10 分钟 · 正在运行', status: '运行中', tone: 'warn', checked: '146 / 248', checkedLabel: '当前进度', changed: '', changedLabel: '59%', progress: '59%', duration: '58s', durationLabel: '已运行', action: '详情' }, { name: '余额采样', meta: '每 30 分钟 · 连续失败 2 次', status: '失败', tone: 'bad', checked: '42', checkedLabel: '检查账号', changed: '7', changedLabel: '采样失败', duration: '09:21', durationLabel: '上次运行', action: '重试' }]
const filteredIssues = computed(() => selectedRisk.value === 'all' ? issues : issues.filter(issue => issue.tags.includes(selectedRisk.value)))
const activeRiskLabel = computed(() => selectedRisk.value === 'all' ? '全部风险' : risks.find(item => item.key === selectedRisk.value)?.label || '全部风险')
const showToast = (message: string) => { toast.value = message; window.clearTimeout(toastTimer); toastTimer = window.setTimeout(() => { toast.value = '' }, 1800) }
const closeDrawer = () => { selectedIssue.value = null; selectedProvider.value = null }
</script>
